/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teatropatito.vista;

/**
 *
 * @author Acer notbook
 */
public class ImprimirReporteVista extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public ImprimirReporteVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ver = new javax.swing.JButton();
        etiquetaObras = new javax.swing.JLabel();
        listaObras = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumenReporte = new javax.swing.JTable();
        regresar = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 325));
        setResizable(false);
        getContentPane().setLayout(null);

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/Consultar.jpg"))); // NOI18N
        getContentPane().add(ver);
        ver.setBounds(480, 230, 110, 51);

        etiquetaObras.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        etiquetaObras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/obras.jpg"))); // NOI18N
        etiquetaObras.setText("Obras");
        getContentPane().add(etiquetaObras);
        etiquetaObras.setBounds(190, 30, 110, 50);

        listaObras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(listaObras);
        listaObras.setBounds(315, 41, 275, 30);

        resumenReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Area Lata:", null, null, null},
                {"Area Cobre:", null, null, null},
                {"Area Plata", null, null, null},
                {"Area Diamante:", null, null, null},
                {"Area Oro:", null, null, null},
                {"Nombre Obra:", null, "Total Ventas:", null}
            },
            new String [] {
                "Title ", "No. Asientos", "Precio", "Total Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resumenReporte.setMaximumSize(new java.awt.Dimension(214783647, 96));
        jScrollPane1.setViewportView(resumenReporte);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(23, 99, 856, 123);

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/Regresar.jpg"))); // NOI18N
        getContentPane().add(regresar);
        regresar.setBounds(300, 230, 110, 51);

        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/imprimirReporte.jpg"))); // NOI18N
        getContentPane().add(imprimir);
        imprimir.setBounds(690, 230, 140, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/PatoteInicial.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/PatoteInicial.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 0, 390, 290);

        setSize(new java.awt.Dimension(918, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirReporteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaObras;
    public javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> listaObras;
    public javax.swing.JButton regresar;
    public javax.swing.JTable resumenReporte;
    public javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
