/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teatropatito.vista;

import javax.swing.JButton;

/**
 *
 * @author GCTec
 */
public class MenuPrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public MenuPrincipalVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearObra = new javax.swing.JButton();
        eliminarObra = new javax.swing.JButton();
        vender = new javax.swing.JButton();
        reembolso = new javax.swing.JButton();
        imprimirReporte = new javax.swing.JButton();
        modificarObra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teatro Patito Feo");
        setBackground(new java.awt.Color(255, 255, 102));
        setFont(new java.awt.Font("Monotype Corsiva", 0, 10)); // NOI18N
        setForeground(java.awt.Color.black);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(510, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(12000, 4000));
        getContentPane().setLayout(null);

        crearObra.setBackground(new java.awt.Color(153, 153, 153));
        crearObra.setFont(new java.awt.Font("Mongolian Baiti", 2, 14)); // NOI18N
        crearObra.setForeground(new java.awt.Color(51, 51, 255));
        crearObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/crear.jpg"))); // NOI18N
        getContentPane().add(crearObra);
        crearObra.setBounds(650, 350, 100, 40);

        eliminarObra.setBackground(new java.awt.Color(153, 153, 153));
        eliminarObra.setFont(new java.awt.Font("Mongolian Baiti", 2, 14)); // NOI18N
        eliminarObra.setForeground(new java.awt.Color(51, 51, 255));
        eliminarObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/eliminar obra.jpg"))); // NOI18N
        getContentPane().add(eliminarObra);
        eliminarObra.setBounds(820, 350, 110, 40);

        vender.setBackground(new java.awt.Color(153, 153, 153));
        vender.setFont(new java.awt.Font("Mongolian Baiti", 2, 14)); // NOI18N
        vender.setForeground(new java.awt.Color(51, 51, 255));
        vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/vender.jpg"))); // NOI18N
        getContentPane().add(vender);
        vender.setBounds(650, 480, 110, 40);

        reembolso.setBackground(new java.awt.Color(153, 153, 153));
        reembolso.setFont(new java.awt.Font("Mongolian Baiti", 2, 14)); // NOI18N
        reembolso.setForeground(new java.awt.Color(51, 51, 255));
        reembolso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/reembolso.jpg"))); // NOI18N
        getContentPane().add(reembolso);
        reembolso.setBounds(820, 480, 110, 40);

        imprimirReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/imprimirReporte.jpg"))); // NOI18N
        getContentPane().add(imprimirReporte);
        imprimirReporte.setBounds(720, 600, 140, 40);

        modificarObra.setText("modificar Obra");
        modificarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarObraActionPerformed(evt);
            }
        });
        getContentPane().add(modificarObra);
        modificarObra.setBounds(500, 400, 160, 70);

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modificarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalVista().setVisible(true);
            }
        });
    }

    public JButton getCrearObra() {
        return crearObra;
    }

    public void setCrearObra(JButton crearObra) {
        this.crearObra = crearObra;
    }

    public JButton getEliminarObra() {
        return eliminarObra;
    }

    public void setEliminarObra(JButton eliminarObra) {
        this.eliminarObra = eliminarObra;
    }

    public JButton getImprimirReporte() {
        return imprimirReporte;
    }

    public void setImprimirReporte(JButton imprimirReporte) {
        this.imprimirReporte = imprimirReporte;
    }

    public JButton getModificarObra() {
        return modificarObra;
    }

    public void setModificarObra(JButton modificarObra) {
        this.modificarObra = modificarObra;
    }

    public JButton getReembolso() {
        return reembolso;
    }

    public void setReembolso(JButton reembolso) {
        this.reembolso = reembolso;
    }

    public JButton getVender() {
        return vender;
    }

    public void setVender(JButton vender) {
        this.vender = vender;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearObra;
    private javax.swing.JButton eliminarObra;
    private javax.swing.JButton imprimirReporte;
    private javax.swing.JButton modificarObra;
    private javax.swing.JButton reembolso;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
