/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teatropatito.vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import lu.tudor.santec.jtimechooser.JTimeChooser;

/**
 *
 * @author ARMC3PO
 */
public class ModificarObraVista extends javax.swing.JFrame {

    /**
     * Creates new form ModificarObraVista
     */
    public ModificarObraVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatoaObra = new javax.swing.JPanel();
        nombreObraLbl = new javax.swing.JLabel();
        nombreObraTxt = new javax.swing.JTextField();
        listaObrasLbl1 = new javax.swing.JLabel();
        ObrasCBX = new javax.swing.JComboBox<>();
        panelDatosFunciones = new javax.swing.JPanel();
        funcionesCBX = new javax.swing.JComboBox<>();
        listaFuncionesLbl = new javax.swing.JLabel();
        horaInicioLbl = new javax.swing.JLabel();
        horaFinLbl = new javax.swing.JLabel();
        FechaLbl = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        horaInicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        minInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        horaFin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        minFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreObraLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombreObraLbl.setText("Nombre:");

        nombreObraTxt.setText("...");

        javax.swing.GroupLayout panelDatoaObraLayout = new javax.swing.GroupLayout(panelDatoaObra);
        panelDatoaObra.setLayout(panelDatoaObraLayout);
        panelDatoaObraLayout.setHorizontalGroup(
            panelDatoaObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatoaObraLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(nombreObraLbl)
                .addGap(78, 78, 78)
                .addComponent(nombreObraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatoaObraLayout.setVerticalGroup(
            panelDatoaObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatoaObraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatoaObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreObraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreObraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaObrasLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listaObrasLbl1.setText("Lista de Obras: ");

        ObrasCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        funcionesCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listaFuncionesLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listaFuncionesLbl.setText("Lista de Obras: ");

        horaInicioLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        horaInicioLbl.setText("Inicio:");

        horaFinLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        horaFinLbl.setText("Fin:");

        FechaLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FechaLbl.setText("Fecha: ");

        horaInicio.setText("00");

        jLabel1.setText("hrs, ");

        minInicio.setText("00");

        jLabel2.setText("mins.");

        horaFin.setText("00");

        jLabel3.setText("hrs, ");

        minFin.setText("00");

        jLabel4.setText("mins.");

        javax.swing.GroupLayout panelDatosFuncionesLayout = new javax.swing.GroupLayout(panelDatosFunciones);
        panelDatosFunciones.setLayout(panelDatosFuncionesLayout);
        panelDatosFuncionesLayout.setHorizontalGroup(
            panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFuncionesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaFuncionesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaLbl))
                .addGroup(panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosFuncionesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(funcionesCBX, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(278, Short.MAX_VALUE))
                    .addGroup(panelDatosFuncionesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(horaInicioLbl)
                        .addGap(8, 8, 8)
                        .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(horaFinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minFin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38))))
        );
        panelDatosFuncionesLayout.setVerticalGroup(
            panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFuncionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaFuncionesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcionesCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosFuncionesLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosFuncionesLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horaFinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(minFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(panelDatosFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(horaInicioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(minInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guardarBtn.setText("Guardar");

        volverBTN.setText("Volver");

        refreshBtn.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(listaObrasLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ObrasCBX, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarBtn)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatoaObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatosFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaObrasLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ObrasCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatoaObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDatosFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(volverBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarObraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarObraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarObraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarObraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarObraVista().setVisible(true);
            }
        });
    }

    public JComboBox<String> getObrasCBX() {
        return ObrasCBX;
    }

    public void setObrasCBX(JComboBox<String> ObrasCBX) {
        this.ObrasCBX = ObrasCBX;
    }

    public JComboBox<String> getFuncionesCBX() {
        return funcionesCBX;
    }

    public void setFuncionesCBX(JComboBox<String> funcionesCBX) {
        this.funcionesCBX = funcionesCBX;
    }

    public JButton getGuardarBtn() {
        return guardarBtn;
    }

    public void setGuardarBtn(JButton guardarBtn) {
        this.guardarBtn = guardarBtn;
    }

    public JDateChooser getFecha() {
        return fecha;
    }

    public void setFecha(JDateChooser jDateChooser1) {
        this.fecha = jDateChooser1;
    }

    public JTextField getNombreObraTxt() {
        return nombreObraTxt;
    }

    public void setNombreObraTxt(JTextField nombreObraTxt) {
        this.nombreObraTxt = nombreObraTxt;
    }

    public JPanel getPanelDatoaObra() {
        return panelDatoaObra;
    }

    public void setPanelDatoaObra(JPanel panelDatoaObra) {
        this.panelDatoaObra = panelDatoaObra;
    }

    public JPanel getPanelDatosFunciones() {
        return panelDatosFunciones;
    }

    public void setPanelDatosFunciones(JPanel panelDatosFunciones) {
        this.panelDatosFunciones = panelDatosFunciones;
    }

    public JButton getRefreshBtn() {
        return refreshBtn;
    }

    public void setRefreshBtn(JButton refreshBtn) {
        this.refreshBtn = refreshBtn;
    }

    public JButton getVolverBTN() {
        return volverBTN;
    }

    public void setVolverBTN(JButton volverBTN) {
        this.volverBTN = volverBTN;
    }

    public JTextField getHoraInicio() {
        return horaInicio;
    }

    public void setHoraInicio(JTextField horaInicio) {
        this.horaInicio = horaInicio;
    }

    public JTextField getMinFin() {
        return minFin;
    }

    public void setMinFin(JTextField minFin) {
        this.minFin = minFin;
    }

    public JTextField getMinInicio() {
        return minInicio;
    }

    public void setMinInicio(JTextField minInicio) {
        this.minInicio = minInicio;
    }

    public JTextField getHoraFin() {
        return horaFin;
    }

    public void setHoraFin(JTextField horaFin) {
        this.horaFin = horaFin;
    }
    
    
    public void inicializarComponentes(){
        initComponents();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaLbl;
    private javax.swing.JComboBox<String> ObrasCBX;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JComboBox<String> funcionesCBX;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField horaFin;
    private javax.swing.JLabel horaFinLbl;
    private javax.swing.JTextField horaInicio;
    private javax.swing.JLabel horaInicioLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel listaFuncionesLbl;
    private javax.swing.JLabel listaObrasLbl1;
    private javax.swing.JTextField minFin;
    private javax.swing.JTextField minInicio;
    private javax.swing.JLabel nombreObraLbl;
    private javax.swing.JTextField nombreObraTxt;
    private javax.swing.JPanel panelDatoaObra;
    private javax.swing.JPanel panelDatosFunciones;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
