/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teatropatito.vista;

import javax.swing.JTextArea;

/**
 *
 * @author GCTec
 */
public class VenderBoletoVista extends javax.swing.JFrame {

    /**
     * Creates new form vender
     */
    public VenderBoletoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        comprar = new javax.swing.JButton();
        listaObras = new javax.swing.JComboBox<>();
        etiquetaObra = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(425, 265));
        setResizable(false);
        getContentPane().setLayout(null);

        comprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/Comprar.jpg"))); // NOI18N
        getContentPane().add(comprar);
        comprar.setBounds(180, 280, 110, 40);

        listaObras.setBackground(new java.awt.Color(0, 0, 0));
        listaObras.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 18)); // NOI18N
        getContentPane().add(listaObras);
        listaObras.setBounds(210, 40, 220, 30);

        etiquetaObra.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        etiquetaObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/obras.jpg"))); // NOI18N
        getContentPane().add(etiquetaObra);
        etiquetaObra.setBounds(80, 30, 110, 50);

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/Regresar.jpg"))); // NOI18N
        getContentPane().add(regresar);
        regresar.setBounds(40, 280, 110, 40);

        consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/Consultar.jpg"))); // NOI18N
        getContentPane().add(consultar);
        consultar.setBounds(340, 280, 110, 40);

        TablaTexto.setColumns(20);
        TablaTexto.setRows(5);
        jScrollPane3.setViewportView(TablaTexto);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(50, 100, 400, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/teatropatito/controlador/fotos/PatoteInicial.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 410);

        setSize(new java.awt.Dimension(525, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    public JTextArea getTablaTexto() {
        return TablaTexto;
    }

    /**
     * @param args the command line arguments
     */
    public void setTablaTexto(JTextArea TablaTexto) {
        this.TablaTexto = TablaTexto;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenderBoletoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenderBoletoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenderBoletoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenderBoletoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenderBoletoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea TablaTexto;
    public javax.swing.JButton comprar;
    public javax.swing.JButton consultar;
    private javax.swing.JLabel etiquetaObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    public javax.swing.JComboBox<String> listaObras;
    public javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
